/*
 * generated by Xtext 2.12.0
 */
package edu.udo.ide

import com.google.inject.Guice
import edu.udo.MGPLRuntimeModule
import edu.udo.MGPLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MGPLIdeSetup extends MGPLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MGPLRuntimeModule, new MGPLIdeModule))
	}
	
}
